name: controller-build

on:
  pull_request_target:
    types: [ closed ]
    branches: [ main ]
    paths:
      - workshop.json
      - .github/workflows/controller-build.yaml
  workflow_dispatch:

concurrency:
  group: build-publish-controller
  cancel-in-progress: true

jobs:
  call-build-publish-controller:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    uses: perftool-incubator/crucible/.github/workflows/build-publish-controller.yaml@master
    with:
      ci_target: "toolbox"
    secrets: inherit
